version: "4.22"
services:
  nginx:
    container_name: testtask_nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    working_dir: /etc/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/testtask
  php:
    container_name: testtask_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    working_dir: /var/www/testtask
    ports:
      - "8000:8000"
    expose:
      - 9003
    volumes:
      - ./:/var/www/testtask
  mysql:
    container_name: testtask_mysql
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    working_dir: /etc/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123123q
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: